### ISSUE TITLE
which the color scheme are you using? looks very nice

### ISSUE THREAD

**Issue by nonkr** [P233/Syntax-highlighting-for-Swift#1]

**Comment by P233** [comment]
Hi @nonkr  it's http://joebergantine.com/projects/color-schemes/birds-of-paradise/

**Comment by Isuru-Nanayakkara** [comment]
I created a version for Xcode. I posted it up on my Github [here](https://github.com/Isuru-Nanayakkara/Earthbound).

**Comment by nonkr** [comment]
@P233 @Isuru-Nanayakkara Thx a lot ;)
